- hosts: localhost
  become: true
  vars:
    userinstall: daryl
  tasks: 
  - name: Install htop
    apt: name=htop
  - name: install prerequisite libraries for erlang 
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400 # 1day
      state: latest
      name:
      - build-essential
      - autoconf
      - m4
      - libncurses5-dev
      - libwxgtk3.0-gtk3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libssh-dev
      - unixodbc-dev
      - xsltproc
      - fop
      - libxml2-utils
      - libncurses-dev
      - openjdk-11-jdk
  - name: sh env
    ansible.builtin.shell:
    args:
      cmd: fish
      chdir: '/home/daryl/'
    register: shenv
  - name: asdf plugin erlang
    ansible.builtin.shell: |
      source /home/{{ userinstall }}/.asdf/asdf.fish
      asdf plugin add erlang
    args:
      executable: fish
  - name: asdf install erlang (for Linux)
    ansible.builtin.shell: |
      source /home/{{ userinstall }}/.asdf/asdf.fish
      asdf install erlang latest
    args:
      executable: fish


